In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([(1,2,3),(4,5,6)])

print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
t=np.transpose(a)
print(t)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [11]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
zeromatrix = np.zeros((2,2))

In [19]:
zeromatrix

array([[0., 0.],
       [0., 0.]])

In [22]:
onesmatrix = np.ones((2,2))

In [23]:
onesmatrix

array([[1., 1.],
       [1., 1.]])

In [33]:
np.append(zeromatrix,onesmatrix)

array([0., 0., 0., 0., 1., 1., 1., 1.])

In [24]:
ins = np.insert(a,2,5)

In [25]:
ins

array([1, 2, 5, 3, 4, 5, 6])

In [36]:
dele = np.delete(a,2)

In [37]:
dele

array([1, 2, 4, 5, 6])

In [30]:
np.concatenate((a,a),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [31]:
np.hstack((a,a))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [32]:
np.vstack((a,a))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [40]:
# empty matrix it create a address for an empty matrix

np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.81810591e-321],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [42]:
# it create matrix with random number
rand=np.random.random((10,10))
rand

array([[0.33248036, 0.77182931, 0.60392075, 0.67540166, 0.9556009 ,
        0.00823193, 0.32383743, 0.47108308, 0.46943478, 0.66747721],
       [0.8536543 , 0.85526207, 0.1708856 , 0.50473398, 0.54414584,
        0.61689775, 0.97516012, 0.15132968, 0.91559332, 0.78652823],
       [0.868602  , 0.35786816, 0.15377416, 0.10053314, 0.32748283,
        0.39490498, 0.32508015, 0.34210753, 0.46078011, 0.95068976],
       [0.46866287, 0.37612142, 0.08501666, 0.67193489, 0.70684704,
        0.25658034, 0.53761634, 0.42190776, 0.34965766, 0.79570135],
       [0.78251081, 0.19311738, 0.89928411, 0.35293798, 0.63023088,
        0.5763673 , 0.35516408, 0.20739457, 0.2832126 , 0.49032374],
       [0.29179875, 0.74625411, 0.24510454, 0.7324291 , 0.50085285,
        0.48344039, 0.26396458, 0.66108105, 0.54079597, 0.30450017],
       [0.36383737, 0.52198691, 0.79176262, 0.09595774, 0.9278353 ,
        0.6420545 , 0.43748863, 0.23081755, 0.44330686, 0.00546571],
       [0.00763165, 0.58794639, 0.4885196